- name: Check MQ processes
  shell: "ps -ef | grep '[a]mq'"
  register: mq_process
  changed_when: false

- name: Fail if no MQ processes found
  fail:
    msg: "No MQ processes running on this host!"
  when: mq_process.stdout_lines | length == 0
