- name: MQ Health Check Workflow
  hosts: all
  gather_facts: False

  roles:
    - { role: mq_ping, tags: ["ping"] }
    - { role: mq_process_check, tags: ["process"] }
    - { role: mq_qm_status, tags: ["qm"] }
    - { role: mq_queues_check, tags: ["queues"] }
    - { role: mq_logs_check, tags: ["logs"] }
    - { role: mq_summary, tags: ["summary"] }